aas-core-works/aas-core-meta

- aas_core_meta/v3rc1.py
> Review on 12.11.2021

- aas_core_meta/v3rc1.py
> From 4.7.8 to 4.7.13. 2021-11-16

- aas_core_meta/v3rc1.py
This patch finalizes V3RC1 with all the models till security, after the
joint session of @sadelko and @manu3756.
> Finish V3RC1 till security model

- .idea/aas-core3-meta.iml
- .idea/misc.xml
- aas_core_meta/marker.py
- aas_core_meta/v3rc1.py
- aas_core_meta/verification.py
This patch makes the meta-model v3rc1 conform to the pre-commit checks
which we will merge in a future pull request.
> Make v3rc1 conform to future pre-commit checks

- .github/workflows/check-commit-messages-in-push.yml
- .github/workflows/check-pull-request-title-and-description.yml
- .github/workflows/ci.yml
- .github/workflows/publish-to-pypi.yml
- .idea/csv-plugin.xml
- .idea/dictionaries/rist.xml
- CONTRIBUTING.rst
- README.md
- README.rst
- aas_core_meta/__init__.py
- aas_core_meta/py.typed
- additional-verbs-in-imperative-mood.txt
- check_init_and_setup_coincide.py
- precommit.py
- setup.py
This patch introduces the pre-commit checks (formatting, mypy, making
sure the meta-models are importable *etc.*).
> Add pre-commit, setup.py and CI

- aas_core_meta/__init__.py
- setup.py
This is a pre-release to test publishing to PyPI.
> Release 2021.11.20a2

- aas_core_meta/marker.py
- aas_core_meta/v3rc1.py
This patch includes various minor fixes so that aas-core-codegen can
translate it into a JSON schema.
> Fix V3RC1 for JSON schema generation

- aas_core_meta/v3rc1.py
This patch includes the classes related to the security to V3RC1.
> Add security part to V3RC1

- aas_core_meta/marker.py
- aas_core_meta/v3rc1.py
- aas_core_meta/v3rc2.py
Co-authored-by: Nico Braunisch <nico.braunisch@tu-dresden.de>
> Implement first draft RC2

- aas_core_meta/v3rc2.py
Changed the Chapter Marks in RC2
> Change Chapter Marks in RC2

- precommit.py
Currently, the precommit fails with exceptions whenever a command
execution fails. This is confusing for the developer since it is hard to
distinguish genuin precommit failures from bugs in the precommit script.
Therefore we log messages to STDERR instead of raising exceptions.
> Log better error messages in precommit

- aas_core_meta/v3rc2.py
Add Serilization
Add REF[...]
Change Enum
> Update in RC2 on 2021-11-26

- .idea/csv-plugin.xml
- aas_core_meta/v3rc2.py
- aas_core_meta/verification.py
This patch includes the fixes necessary so that we can generate the JSON
schema for it. We merely reacted to errors returned by the code
generator.
> Fix V3RC2 for code generation

- aas_core_meta/v3rc1.py
We compared the generated SHACL schema against the "official" one. This
patch contains all the resolved differences.
> Update V3RC01 after a round of SHACL review

- aas_core_meta/v3rc1.py
We went once more over the book and fixed the properties of the data
specifications.
> Fix data specifications in V3RC01

- aas_core_meta/v3rc1.py
We fix minor plurals/singulars in V3RC01 after comparing the generated
schema against the official one.
> Fix V3RC01 after diffing official JSON schema

- aas_core_meta/v3rc1.py
We polish V3RC01 so that it also complies with aas-core-codegen, which
we want to include in our pre-commit checks.
> Make V3RC01 comply with aas-core-codegen

- .idea/csv-plugin.xml
- .idea/dictionaries/rist.xml
- aas_core_meta/v3rc1.py
- aas_core_meta/v3rc2.py
- tests/test_v3rc2.py
We go through the meta-model and write out the missing invariants.
Along the way, we fix all the errors and inconsistencies we could find.
> Write the invariants for V3RC02

- CHANGELOG.rst
- aas_core_meta/__init__.py
- setup.py
* Remove data specifications from V3RC02 (#61)
> Release 2022.4.30a4

- CHANGELOG.rst
- aas_core_meta/__init__.py
- setup.py
* Fix dangling references in V3RC02 (#63)
> Release 2022.4.30a5

- aas_core_meta/v3rc2.py
We remove the class ``View`` from V3RC02 as it has been also removed in
the book.
> Remove class ``View`` from V3RC02

- CHANGELOG.rst
- aas_core_meta/__init__.py
- setup.py
* Remove class ``View`` from V3RC02 (#65)
> Release 2022.4.30a6

- aas_core_meta/v3rc2.py
We fix the reference implementation of the invariants while we are
translating them for aas-core3.0rc02-csharp.
> Fix invariants in V3RC02

- aas_core_meta/v3rc2.py
- tests/test_v3rc2.py
We extend the regular expressions from [the official XML docs] to
include the number of decimals in finite integers.
[the official XML docs]: https://www.w3.org/TR/xmlschema11-2/
> Fix cardinalities in patterns of V3RC02

- aas_core_meta/v3rc2.py
Update the Referencing to Version 3.0 RC02 Version
> Revise Referencing

- aas_core_meta/v3rc2.py
Rename Submodel_element_struct to Submodel_element_collection
This was necessary to achieve compliance with rc02
> Revise Submodel_element_collection

- aas_core_meta/v3rc2.py
Add Attribute Qualifier_type in Qualifier and 
Enumeration for kinds of qualifiers.
This was necessary to achieve compliance with rc02.
A
> Revise Qualifier with Qualifier_type

- aas_core_meta/v3rc2.py
* Resource: Asset_kind --> Path_type
* Several updates to explanations
* Specific_Asset_Id.external_subject_id is not optional
* Several updates to the new sections in the PDF
* Blob.MIME_type --> Blob.content_type
* Fragment_keys has no Global_reference
> Refactor sections 5.7.3 to 5.7.10 of RC02

- aas_core_meta/v3rc2.py
Readd class DataSpecification from section 6.2 and add 
abstract class DataSpecificationContent from section 6.2. 
This was necessary because of the need of in the schema 
generation.
> Add DataSpecification and Content

- README.rst
Add new Contributor to README.md
> Change Contributors

- aas_core_meta/v3rc2.py
- setup.py
We compare our meta-model against the book for the Sections in the
finalized version of the book, and fix the inconsistencies.
Since we use ``any`` in the invariants, we have to upgrade
aas-core-codegen to 0.0.10.
> Review V3RC02 for Sections 5.7.2 to 5.7.6

- .idea/dictionaries/rist.xml
- aas_core_meta/v3rc2.py
We finally understood the text of the constraint and formalize it in the
meta-model through this patch.
> Introduce constraint AASd-116 in V3RC02

- .idea/dictionaries/rist.xml
- aas_core_meta/v3rc2.py
- setup.py
- tests/test_v3rc2.py
We compare our meta-model against the book and make changes either to
our meta-model or report findings and inconsistencies back to the
authors of the book.
> Review V3RC02 for Sections 5.7.7 to 5.7.12

- CHANGELOG.rst
- aas_core_meta/__init__.py
- setup.py
This is the version of our meta-model tailored to the finalized version
of the book for V3RC02.
> Release 2022.5.26

- CHANGELOG.rst
- aas_core_meta/__init__.py
- setup.py
In this version we fix a couple of inconsistencies with the book which
were spotted during the reviews.
* Sort out ``modelType`` in V3RC02 (#104)
* Make ``RelationshipElement`` concrete in V3RC02 (#103)
> Release 2022.6.3

- precommit.py
- tests/test_v3rc2.py
We re-format test code to make the diffs minimal.
> Include tests in re-formating

- aas_core_meta/v3rc2.py
- tests/test_v3rc2.py
It has become clear that the text of AASd-119 is indeed correct after a
mail correspondence with the authors of the book. Hence, we revert it
back to its original state.
> Revert back AASd-119 in V3RC02

- aas_core_meta/v3rc2.py
We document a post-condition in the getter-or-default for the category
of a data element in V3RC02.
> Ensure Data elmeent category in V3RC02

- CHANGELOG.rst
- aas_core_meta/__init__.py
- setup.py
This is a minor enhancement version. We implement the invariant on
the category of a data element in a more systematic manner.
* Encapsulate data element category in V3RC02 (#121)
* Ensure Data element category in V3RC02
> Release 2022.6.21

- aas_core_meta/v3rc2.py
Change the URL for reference in the book
> Update book url

- aas_core_meta/v3rc2.py
We made a mistake and diverged from the book. See [this issue] in
adminshell-io/aas-specs repository.
[this issue]: https://github.com/admin-shell-io/aas-specs/issues/193
> Make specific asset IDs a list in V3RC02

- aas_core_meta/v3rc2.py
- tests/test_v3rc2.py
We fix the enumeration literals in the subsets of ``Key_types``.
Fixes #131.
Replaces #132.
> Add ``Identifiable`` in ``AAS_Identifiables``

- aas_core_meta/v3rc2.py
We formalize the constraints AASd-121 to 128 using index access and
for-loops over ranges.
> Use index access and for-in-range in constraints

- precommit.py
If the command could not be executed since the file could not be found,
we catch the exception instead of blowing up as the stack trace is scare
and uninformative for the user.
> Handle ``FileNotFound`` in precommit script

- aas_core_meta/v3rc2.py
We remove the data specifications from the Environment in V3RC02.
> Remove data specifications from Environment

- .github/workflows/test-generate-doc.yml
> Fix generate-doc workflow

- .github/workflows/generate-doc.yml
We change the generate doc workflow to respond to pushes to the main branch.
> Generate docs on pushes to main branch

- htmlgen/for_metamodel.py
Usages of our types are very handy when examining the meta-model as a whole, and tracing how it all fits together.
For a longer discussion and the background, see [this relevant issue] on aas-core-codegen.
[this relevant issue]: https://github.com/aas-core-works/aas-core-codegen/issues/29
> Generate usages for our types in htmlgen

- .idea/dictionaries/rist.xml
- aas_core_meta/v3.py
- tests/common.py
- tests/test_v3.py
This is the initial version of the formalized V3 meta-model translated from the book.
The book has not been published yet! This version is intended only for the review.
> Write first draft of V3 of the meta-model

- aas_core_meta/v3.py
We fix the book version as it was a trail from the V3RC02.
> Fix book version in V3

- aas_core_meta/v3.py
We update the description of the literals of `Modelling_kind` to latest state of the book.
> Update docs of `Modelling_kind` in V3

- aas_core_meta/v3.py
We change the order of enumeration literals to reflect better the tables in the book.
> Change order of enum literals in V3

- aas_core_meta/v3.py
> Adapt module docstring

- aas_core_meta/v3.py
See #206
Chapter 5.3.4, page 68
https://nextcloud.s-heppner.com/index.php/s/2KZr2kHoSTjkSoi#page=68
> Add missing value of Asset_kind enum

- aas_core_meta/v3.py
Wherever possible, we referenced DotAAS Part 1a.
When necessary, we added an inline comment when referencing DotAAS Part 3a
> Update existing refs to the current version of the book

- aas_core_meta/v3.py
- setup.py
- tests/test_v3.py
We implement the constraint AASd-117 by help of assertion tests.
This supersedes #254.
Fixes #253.
> [V3] Implement Constraint AASd-117

- tests/common.py
- tests/test_v3.py
We refactor the test code to `tests.common` module to make it available to future meta-model versions.
> Refactor code from `test_v3` to `common`

- aas_core_meta/v3.py
Fix the implementation of invariant for `AASd-014` by adding a missed check for `entity_type`.
Fix #259
> Add a check for `entity_type` in invariant for `AASd-014`

- aas_core_meta/v3.py
We forgot to update the constructors after #264, and fix the issue in this patch.
> [V3] Fix constructors of `Identifiable`'s

- aas_core_meta/v3_1.py
In order to avoid confusion, we add a WIP notice to the module docstring.
> v3.1: Add WIP notice in docstring
