aas-core-works/aas-core-meta

aas_core_meta/v3rc1.py
We replace `*_uri` to `*_URI` to make for better identifiers in target
languages.
=> Rename `URI` abbreviations

aas_core_meta/v3rc1.py
This patch removes the aliasing of built-in types such as
`Value_data_type` for `str` *etc.*
=> In-line type aliases

aas_core_meta/marker.py, aas_core_meta/v3rc1.py, aas_core_meta/v3rc2.py
Co-authored-by: Nico Braunisch <nico.braunisch@tu-dresden.de>
=> Implement RC2 up to 6.8.2.3 in the book

aas_core_meta/v3rc1.py
We compared "official" JSON Schema [1] against the generated ones, and
changed the meta-model for V3RC1 accordingly. Mind that many parts of
the "official" JSON Schema were not documented properly in the book [2],
so we had to leave them out in the meta-model as well.
[1]: https://github.com/admin-shell-io/aas-specs/blob/master/schemas/json/aas.json
[2]: https://www.plattform-i40.de/IP/Redaktion/DE/Downloads/Publikation/Details_of_the_Asset_Administration_Shell_Part1_V3.pdf?__blob=publicationFile&v=5
=> Change V3RC1 after diff against the JSON Schema

.idea/aas-core3-meta.iml, .idea/misc.xml, aas_core_meta/marker.py, aas_core_meta/v3rc1.py
We introduce a generic class as a marker for references which are
represented with `ref*` in the book.
In this patch, we fix only v3RC1 and leave V3RC2 for the following
patches.
=> Introduce `Ref` marker

aas_core_meta/marker.py, aas_core_meta/v3rc1.py
This marker helps us model the relationships between different
enumerations. We need the marker since Python does not support
inheritance of enumerations.
=> Introduce `is_superset_of` marker

aas_core_meta/marker.py, aas_core_meta/v3rc1.py
The serialization needs to specify the concrete type since the given
type is abstract and the implemented de-serializations need to know
the concrete type up-front.
Therefore, the previous JSON serialization settings generalize also to
all serializations (including XML).
=> Rename `json_serialization` to `serialization`

aas_core_meta/v3rc1.py
The `Constraint` shows up in properties, but it is an abstract class.
Therefore, the deserializers need to know the model type upfront.
=> Make `Constraint` model-typed in V3RC1

aas_core_meta/v3rc2.py
We forgot to propagate the renames of the ``value`` attribute to the
constructor in #30. This patch fixes the issue.
=> Fix omitted renames in V3RC02

aas_core_meta/v3rc1.py
This patch comprises post-fixes which were omitted by mistake after the
review against the "official" SHACL schema for V3RC01.
=> Make postfixes after SHACL review of V3RC01

aas_core_meta/v3rc1.py, aas_core_meta/v3rc2.py
We include structured references for constraints. They are necessary
so that it is easier to generate links in the browsable documentation.
=> Write constraint references as `:constraintref:`

aas_core_meta/v3rc1.py, aas_core_meta/v3rc2.py
We need to make the root-level lists in the environment optional so that
JSON and SHACL schemas coincide. Moreover, this makes the handling of
lists consistent across the meta-model since all the other lists are
marked as optional.
=> Make properties optional in AAS environment

aas_core_meta/v3rc2.py
This is an update of the Python metamodel to the state of 
`DotAAS V3.0 RC02` as documented by 2022-02-20. 
This was necessary because a new version of the document is being 
updated for RC02. First, all classes and attributes from chapter 5.7.2 
up to and including chapter 5.7.6 and chapter 5.7.8 up to and including 
chapter 5.7.11 were revised.
=> Revise python metamodel according to current RC02

.idea/dictionaries/rist.xml, precommit.py, setup.py
We add the latest version of aas-core-codegen to the pre-commit checks
so that we discover meta-model inconcisistencies as early as possible.
=> Add aas-core-codegen to pre-commit checks

aas_core_meta/v3rc2.py
We type out the references in the documnetation using our pre-defined
Sphinx notation throughout the meta-model so that they can be properly
included in the code and schema generation.
Additionally, we make the literals explicit by using double backticks.
=> Fix references to classes and attributes in V3RC02

aas_core_meta/v3rc2.py
The UAG Verwaltungsschale does not consider "ID" to be an initialism and
thus they write it everywhere as a non-abbreviation (as opposed to IEC,
which is written as upper-case). This is relevant for camelCase
identifiers.
=> Make `id` lowercase

aas_core_meta/v3rc2.py
We make all `0..*` lists optional to avoid confusion and be a bit more
consistent with the book. In the future, we should add invariants that
the lists must not be empty if specified.
=> Make all lists optional in V3RC02

setup.py
We had problems on the remote CI server, so we update black to the
latest version.
=> Upgrade `black` to 22.3.0

aas_core_meta/v3rc2.py
The time stamps need to be in UTC, so we have to make invariants on the
strings.
=> Introduce `Date_time_stamp_UTC` in V3RC02

aas_core_meta/v3rc2.py
This change removes double patterns and double constrained primitives.
Notably, `MIME_typed` goes away and we introduce `Content_type`
according to the book.
Furthermore, we set the correct references in the book (according to the
latest version -- though these are always in flux).
Finally, we make `Value_data_type` a string to reflect that it can
contain *any* value of the XML basic types.
=> Sort out constrained primitives

aas_core_meta/v3rc2.py
There was a dangling reference in the data specification. We referred to
the attribute `category`, but the data specification is referred to and
has no attribute `category`.
This dangling reference has not been discovered due to the bug in
aas-core-codegen.
=> Fix dangling reference in data specs for V3RC02

CHANGELOG.rst, aas_core_meta/__init__.py, setup.py
This is a pre-release of the major release coming up on 2022-04-30.
* Revisit V3RC01 and V3RC02 according to the current state of the book.
* Formalize the constraints as invariants for V3RC02.
=> Release 2022.4.30a1

aas_core_meta/v3rc2.py
We remove redunadant nullability checks in invariants for non-optional
properties. These redundancies became only clear when we generated and
compiled the C# code.
=> Remove redunant nullability checks in V3RC02

CHANGELOG.rst, aas_core_meta/__init__.py, setup.py
* Remove redundant nullability checks in V3RC02 (#55)
* Fix docstring for ``matches_BCP_47`` in V3RC02 (#54)
=> Release 2022.4.30a2

aas_core_meta/v3rc2.py
This was necessary because of the mismatch in the spec. DotAAS names 
the possible entry "FragmenId" of the attribute type from class key 
with the type key_elements. The Class Key_elements has no entry for 
"FragmentId". To this end, we renamed FragmentId to FragmentReference.
=> Revise class key and class key_elements

setup.py
We use ``aas-core-codegen`` to run smoke tests in order to ensure that
the meta-models can be translated into programming code and schemas.
This helps us discover the errors as early as possible.
=> Update ``aas-core-codegen`` to 0.0.7

.gitignore, aas_core_meta/v3rc2.py
We re-order the classes in V3RC02 to make the diff from the RC01 as
minimal as possible.
Additionally, we make all the minor changes to sync up with the current
working version of the meta-model. Note, however, that the working
version is still unstable, so many more changes are expected in the
future.
=> Re-order V3RC02 classes to match V3RC01

obsolete/2022-04-09/v3rc02-with-data-specifications/v3rc2.py
The data specifications are not part of the core meta-model so we remove
them. They are kept in ``obsolete/`` directory for future reference.
=> Remove data specifications from V3RC02

aas_core_meta/v3rc2.py
We mistakenly omitted to run the pre-commit script and there were a
couple of dangling constraint references since we removed the data
specifications from V3RC02.
=> Fix dangling references in V3RC02

aas_core_meta/v3rc2.py
We fix the invariant that checked the value of a category such that it
only applies if the category has been set, as the category is an
optional property.
=> Check category only if set in V3RC02

aas_core_meta/v3rc2.py
We had a mistake in the invariant of the ``Entity`` class that was
always failing. Namely, we have to XOR global asset ID and specific
asset ID, but we simply XOR'ed the values with themselves.
=> Fix the non-sensical invariant in Entity in V3RC02

aas_core_meta/v3rc2.py
We remove the assignment of default values to properties in constructors
in V3RC02 since the book is not explicit about how this should be
implemented. If we set the properties to default values, the client can
not distinguish anymore between the case "no value provided" and "the
explicit value has been provided".
While it might be easier for the client to simply see what value is
there (and many clients might want to disregard the case whether it was
simply the default set in constructor or the actual explicit assignment
of a value), this behavior also makes for surprising round-trip logic
where the de-serialization -- serialization does not give the result
equal to the expected starting point.
=> Remove setting default values in constructors

aas_core_meta/v3rc2.py
In #70, we removed the assignments to default values in the constructors
in order to be able to test for round-trip conversions free of side
effects. This makes the life of the clients a bit more cumbersome as it
forces them to litter their code with countless ``if X is null then
default value`` checks.
In this patch, we introduce for each property with a default value a
getter method which returns the default value if the property is null.
We currently implemented this with implementation-specific methods. This
is admittedly error-prone and does not conform with the idea that most
code should be automatically generated. Unfortunately, we lack time at
the moment as we focus on the release of the schemas and C# SDK which,
on their part, need automatically generated test data.
When the time …
=> Introduce `get_*_or_default` as methods to V3rc2

CHANGELOG.rst, aas_core_meta/__init__.py, setup.py
* Introduce ``get_*_or_default`` as methods to V3rc2 (#71)
* Remove setting default values in constructors (#70)
* Fix the nonsensical invariant in Entity in V3RC02 (#69)
* Check category only if set in V3RC02 (#68)
* Fix invariants in V3RC02 (#67)
=> Release 2022.5.30a1

aas_core_meta/v3rc2.py
We use attribute references (``:attr:``) to reference default values for
the properties. This is useful as we would be reported an error if we
ever remove the referenced object from the meta-model, but forget to
update the documentation of a property.
=> Reference default values in V3RC02

.idea/dictionaries/rist.xml, aas_core_meta/v3rc2.py, tests/test_v3rc2.py
XML standard disallows `NUL` character and it can't be even encoded. We
therefore add a verification for such a character as a pattern.
=> Add verification for `xs:string` in v3RC02

tests/test_v3rc2.py
We explicitly document that the scientific notation is not allowed for
``xs:decimal`` since that was not immediately clear without thoroughly
studying the regular expression.
=> Test for scientific notation in ``xs:decimal``

aas_core_meta/v3rc2.py
We figured out that the text of the constraint in the book had an error.
The implication should be reversed. Hence we fix the constraint in our
meta-model hoping that it will be fixed in the book as well.
=> Fix constraint AASd-119 in V3RC02

aas_core_meta/v3rc2.py
We omitted "-s" suffixes in a couple of properties in V3RC02. This patch
fixes the names.
=> Fix plurals in V3RC02

precommit.py
We run unit tests in pre-commit since we now add crucial tests for the
meta-model and assertions in there.
=> Execute unit tests in pre-commit

aas_core_meta/v3rc2.py, tests/test_v3rc2.py
A couple of names were inconsistent. We add assertion to the tests to
ensure that the mistakes in naming do not re-appear.
=> Fix naming in V3RC02

tests/test_v3rc2.py
We add unit tests to assert that the enumeration literals related to the
classes are properly specified so that no literal is neither missing nor
superflouous.
This is necessary so that we can easily detect mismatch in the
enumerations against the actual class hierarchy.
=> Assert that literals correspond to classes

aas_core_meta/v3rc2.py
We add a note explaining why the constraint AASd-115 is rather a
guideline than a constraint in the strict sense
(`semantic_id_list_element` should be assumed if the elements of
Submodel Element List have no semantic ID specified).
=> Add note about AASd-115 in V3RC02

aas_core_meta/v3rc2.py
We marked the class `RelationshipElement` abstract by mistake. It is
concrete in the book.
Fixes #97.
=> Make `RelationshipElement` concrete in V3RC02

aas_core_meta/v3rc2.py
We re-visit the serialization settings as we mistakenly set `modelType`.
For some classes, it was redundant since they inherit from `Referable`.
Other classes, such as `Qualifier`, had it set by mistake as a remnant
from a previous refactoring.
Fixes #100, #101, #102.
=> Sort out `modelType` in V3RC02

aas_core_meta/v3rc2.py
We mistakenly copy/pasted the invariant from a class. This broke the
invariant as the ID-short is now a constrained primitive.
=> Fix length invariant of id-shorts in V3RC2

aas_core_meta/v3rc2.py
We make the invariant culturally-explicit by specifying the regular
expression. The invariant involves case-folding which is
culture-specific, but we assume English here.
=> Fix invariant on specific_asset_id in V3RC2

CHANGELOG.rst, aas_core_meta/__init__.py, setup.py
This is a bug-fix version, where our spec turned out to be  incorrect
from the programming point of view.
* Fix invariant on specific_asset_id in V3RC2 (#108)
* Fix length invariant of id-shorts in V3RC2 (#107)
* Fix AnyURI patterns for UTF-32 (#106)
=> Release 2022.6.17

aas_core_meta/v3rc2.py
The elements in a ``Submodel_element_list`` should have no ID-shorts,
hence also no unique ID-shorts.
=> Remove unique idShort from list elements in V3RC02

aas_core_meta/v3rc2.py
The constraint involves an ill-defined comparison between a string and a
reference, so we could not implement it.
=> Remove ill-defined constraint 116 from V3RC02

aas_core_meta/v3rc2.py, tests/test_v3rc2.py
We explicitly check for "is not None" in the invariants corresponding to
AASd-119 as the verification raises null assertions otherwise.
=> Fix nullness in inv. AASd-119 in V3RC02

aas_core_meta/v3rc2.py
We need to explicitly check that the message broker is specified in the
invariant, lest a null exception is raised.
=> Check non-none of message broker in inv. of V3RC02

aas_core_meta/v3rc2.py, tests/test_v3rc2.py
The previous pattern was too permissive and did not follow the
specification by the letter. We also learned a great deal about UTF-16
and UTF-32 along the way, so the previous pattern was also a reflection
of our own ignorance.
=> Fix `xs:string` pattern for V3RC02

aas_core_meta/v3rc2.py, additional-verbs-in-imperative-mood.txt, tests/test_v3rc2.py
We invert the implication in the constraint AASd-119 as it made no sense
to us. We reported the mistake to the authors of the book, and continue
developing under assumption that the text of the constraint will
eventually change.
=> Invert AASd-119 in V3RC02

.idea/dictionaries/rist.xml, CHANGELOG.rst, aas_core_meta/__init__.py, setup.py
This is a version with fixes which were necessary for generating
the JSON test data automatically using aas-core3.0rc02-testgen,
and making sure that the aas-core-codegen generates the C# code
such that it passes all the unit tests for JSON.
XML tests are still pending.
* Invert AASd-119 in V3RC02 (#116)
* Fix ``xs:string`` pattern for V3RC02 (#115)
* Check non-none of message broker in inv. of V3RC02 (#114)
* Fix nullness in inv. AASd-119 in V3RC02 (#113)
* Remove ill-defined constraint 116 from V3RC02 (#111)
* Remove unique idShort from list elements in V3RC02 (#110)
=> Release 2022.6.19

aas_core_meta/v3rc2.py
We forgot to add an invariant to ensure that the extension's value
matches its XSD type.
=> Enforce Extension value match type in V3RC02

CHANGELOG.rst, aas_core_meta/__init__.py, setup.py
This is a minor bug-fix version. We release it so we can start working
on tests with XML data.
* Enforce Extension value match type in V3RC02 (#119)
* Revert back AASd-119 in V3RC02 (#118)
=> Release 2022.6.20

aas_core_meta/v3rc2.py
We have to make ``DataSpecificationContent`` concrete so that we can
effectively test the ``Environment`` with a complete test example.
=> Make ``DataSpecificationContent`` concrete

aas_core_meta/v3rc2.py, additional-verbs-in-imperative-mood.txt
The constraint AASd-107 requires a reference comparison, but the
reference comparison has not been properly defined. Therefore we
introduce a separate function to formalize that references are compared
by their keys and type.
=> Formalize reference comparison in V3RC02

aas_core_meta/v3rc2.py
According to the book, "5.7.10.5 Matching Algorithm for References",
references should be compared only by values and the types in the keys
as well as the type of the reference should be ignored.
Fixes #130.
=> Compare references by values only in V3RC02

aas_core_meta/marker.py, aas_core_meta/v3rc2.py, obsolete/2022-04-09/v3rc02-with-data-specifications/v3rc2.py, obsolete/2022-06-30/v3rc1.py, tests/test_v3rc2.py
This is a major change. We introduce constants in the meta-model
including constant primitive values, constant sets of primitive values
as well as constant sets of enumeration literals.
The continuous integration is expected to fail as we change
aas-core-codegen in parallel, and this change is incompatible with the
current main branch of aas-core-codegen.
=> Introduce constants

setup.py
We update the dependencies to [aas-core-codegen 6b55dbc] so that the
continuous integration, which failed as planned in the previous commit,
can now pass.
[aas-core-codegen 6b55dbc]: https://github.com/aas-core-works/aas-core-codegen/commit/6b55dbc
=> Update aas-core-codegen to 6b55dbc

setup.py
We update the aas-core-codegen as dependency to
[aas-core-codegen f698a1c]. In the previous commit, the remote CI failed
as we had to update both aas-core-meta and aas-core-codegen in sync.
With this change, the remote CI runs again.
[aas-core-codegen f698a1c]: https://github.com/aas-core-works/aas-core-codegen/commit/f698a1c
=> Update aas-core-codegen to f698a1c

aas_core_meta/v3rc2.py
We remove the non-implementation marker for general verification
function which current aas-core-codegen can transpile.
The remove continuous integration is expected to fail as we are
introducing breaking changes in sync between aas-core-codegen and
aas-core-meta. The CI will be restored in the following commit.
=> Make transpilable general verification function

setup.py
We update to [aas-core-codegen a2ba2a5] so that the remote CI runs
again which was intentionally broken in [ab276a8].
[ab276a8]: https://github.com/aas-core-works/aas-core-meta/commit/ab276a88135af94ba14fddc162a94ed1ac574758
[aas-core-codegen a2ba2a5]: https://github.com/aas-core-works/aas-core-codegen/commit/a2ba2a5
=> Update to aas-core-codegen a2ba2a5

aas_core_meta/v3rc2.py
We add a constraint that the references to data specifications in
``Has_data_specifications`` must be global.
=> Make data specification references global in V3RC2

aas_core_meta/v3rc2.py, additional-verbs-in-imperative-mood.txt
Concerning the data specifications, we embed them within
`Has_data_specification` instead of referencing them *via* a global
reference. The working group decided to change the rules for
serialization *after* the book was published. The data specifications
are critical in applications, but there is no possibility to access
them through a data channel as they are not part of an environment.
=> Embed data specifications in V3RC02

aas_core_meta/v3rc2.py
This is merely a cosmetic change in code, no semantics involved.
=> Remove redundant parentheses in V3RC02

aas_core_meta/v3rc2.py
We define the XML namespace for the whole meta-model. This is necessary
so that the generation of XSD, RDF+SHACL schemas and XML
de/serialization are all in sync.
The continuous integration is expected to fail, as it depends on
aas-core-codegen which also needs to change in sync.
=> Define XML namespace

setup.py
We upgrade the version of aas-core-codegen used in continuous
integration to dac0ca1 since it included breaking changes which we had
to update in sync with aas-core-meta.
The continuous integration is now expected to pass.
=> Upgrade aas-core-codegen to dac0ca1

aas_core_meta/v3rc2.py, tests/common.py, tests/test_v3rc2.py
We add an assertion in the tests to check that we infer the minimum
length for all the lists to be 1 except for lists where the end user
defines the semantic (*i.e.*, `Submodel_element_list` and
`Submodel_element_collection`).
This change is necessary so that we avoid ambiguity for the end users
since the distinction in semantics of a null list and an empty list is
not well-defined.
=> Enforce that lists have min. length 1 in V3RC02

setup.py, tests/common.py, tests/test_v3rc2.py
Previously, we used Python ``inspect`` to iterate over the symbols in
the aas-core-meta in the tests. This is cumbersome and misses a lot of
edge cases.
Therefore, we leverage aas-core-codegen, parse the model into the
intermediate representation and perform checks on the intermediate
representation instead.
=> Refactor tests to use aas-core-codegen

.idea/csv-plugin.xml, aas_core_meta/v3rc2.py, setup.py, tests/common.py, tests/test_v3rc2.py
We mistakenly modelled ``Lang_string_set`` as a class instead of a list
(see the issue #128). With this change, we de-structure all
``Lang_string_set`` as lists.
Additionally, we enforce that the affected properties have
the appropriate invariants defined through automatic tests.
Fixes #128.
=> Convert ``Lang_string_set`` to a list in V3RC02

aas_core_meta/v3rc2.py
We remove the nullability check in the invariants in
``Data_specification_physical_unit`` for the property ``definition``
since it is not optional.
While the semantic did not change, the C# compiler complained about the
nullability since it could not be inferred anymore.
=> Remove redundant nullability check in V3RC02

aas_core_meta/v3rc2.py
We formalize the invariants for the concept descriptions since now the
data specifications are embedded.
We make the verification functions implementation-specific since the
casts are very clumsy to formalize and transpile in a readable way
across languages. For example, since Python does not have
a null-coalescing operator, formalizing the constraints such as
``AASc-004`` would involve walrus operator and would result in
an unreadable invariant.
Therefore, we decided to encapsulate the logic in these few functions
and estimate the maintenance effort to dwarf the effort needed to get
this right in aas-core-codegen.
=> Write invariants for data specifications in V3RC02

aas_core_meta/v3rc2.py
We describe all the invariants in V3RC02 with a human-readable text. In
consequence, this gives us human-readable messages in the SDKs. Such
messages are important when the programs are used by non-programmers,
such as GUI editors.
At this point, we also change all ``> 0`` to ``>= 1`` in invariants, so
that the formalized condition matches better the invariant description.
=> Describe all invariants in V3RC02

aas_core_meta/v3rc2.py
We replace "null" with "not set" in the invariant descriptions to obtain
invariant descriptions which generalize better across different
programming languages. For example, "null" is "none" in Python, so this
could cause some confusion.
=> Change "null" to "not set" in invariants

aas_core_meta/v3rc2.py, additional-verbs-in-imperative-mood.txt
We removed the invariant on the pattern since it is doubly checked in
the ``matches_xs_date_time_stamp_utc`` and
``is_xs_date_time_stamp_utc``. However, this was a mistake as we now can
not infer the pattern for the schemas and test generation.
Therefore, we re-introduce the invariant.
=> Re-introduce the pattern for date/time stamps UTC

setup.py
We update to [aas-core-codegen b8e378f] so that the continuous
integration forces all invariants to have a description.
[aas-core-codegen b8e378f]: https://github.com/aas-core-works/aas-core-codegen/commit/b8e378f
=> Update to aas-core-codegen b8e378f

.idea/.gitignore, aas_core_meta/v3rc2.py, tests/test_v3rc2.py
Originally, we left out the constraint on
``Submodel_element_list.value`` and
``Submodel_element_collection.value`` related to the length as we wanted
to allow the distinction between null lists and empty lists, which the
user could define per semantic ID.
However, this is problematic as many users are not aware of the
distinction. Therefore, we keep consistency with all the other lists in
the meta-model.
=> Enforce min. length on submodel element value

aas_core_meta/v3rc2.py
We erroneously transribed from the book ``valueReferencePairTypes``
whereas the correct name of the attribute was ``valueReferencePair`` in
the class ``ValueList``.
=> Fix mistake with ``valueReferencePairTypes``

aas_core_meta/v3rc2.py
So far, we referenced the properties as properties of a concrete class
in the documentation instead of referencing them to the most abstract
class which defines them.
This creates problems with [docfx] in C# so we reference the
properties as properties of the abstract class.
[docfx]: https://dotnet.github.io/docfx/index.html
=> Reference properties from interfaces

aas_core_meta/v3rc2.py
We strip the subdomain and add the HTTPS protocol to follow the
conventions.
See the issue: https://github.com/admin-shell-io/aas-specs/issues/75
=> Change XML namespace to a conventional one

aas_core_meta/v3rc2.py
We fix the casing of the enumeration literals ``Direction`` and
``State_of_event``. We transcribed the upper case from the book by
mistake.
This was the original issue:
https://github.com/admin-shell-io/aas-specs/issues/214
=> Fix casing of some enumeration literals

aas_core_meta/v3rc2.py
In the V3RC02, we mistakenly capitalized the data type, where it should
have been named ``xs:nonNegativeInteger`` (lowercase first).
=> Fix wrong case in ``xs:NonNegativeInteger``

aas_core_meta/v3rc2.py
While working on Python SDK, we noticed a couple of documentation errors and fix them in this patch.
=> Fix minor cosmetics in documentation

aas_core_meta/v3rc2.py, setup.py
Previously, due to ignorance, we annotated references with different prefixes (attributes with ``~`` and classes and constants with ``.``). Eventually, we learned more about Sphinx and how it deals with references (see [1]).
In this change, we sort out the referencing and make it a bit clearer:
* attributes, classes and constants must be references as-are,
* appearance prefixes ``!`` and ``~`` are ignored (as target languages usually do not work like Sphinx), and
* relaxed qualified names (references prefixed with a ``.``) are disallowed as we can only resolve references *within* the meta-model and not outside it.
This change is harmonized with the respective change in [aas-core-codegen 46ddb38f].
[1]: https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#xref-syntax …
=> Sort out references

aas_core_meta/v3rc2.py, tests/test_v3rc2.py
We fix the pattern in V3RC02 for ``xs:float`` and ``xs:double`` as the previous pattern allowed for partial matches and non-integer exponents.
=> Fix pattern for ``xs:float`` and ``xs:double``

aas_core_meta/v3rc2.py, tests/test_v3rc2.py
We disallow the positive sign in front of ``xs:float`` and ``xs:double`` as they are not part of the valid lexical representation.
See also [1] for more details.
[1]: https://www.oreilly.com/library/view/xml-schema/0596002521/re67.html
=> Disallow positive-signed `xs:float` and `xs:double`

aas_core_meta/v3rc2.py, tests/test_v3rc2.py
Unfortunately, we had a bug in aas-core-codegen e2a7a806 (2022-10-30) and prior versions where we generated the names for JSON and RDF schemas based on a hard-wired list of abbreviations in *aas-core-codegen* instead of relying on the naming in aas-core-meta. This list has not been updated before publishing the schemas, so we have to stick with the unexpected casing in the names. To maintain the compatibility with the schemas, we allow for capitalization of certain abbreviations where uppercase would be expected. Concretely, this was the case with abbreviations "AAS" and "XSD".
=> Sync naming with the published schemas for V3RC02

aas_core_meta/v3rc2.py
We introduced a couple of unexpected double whitespaces in the docstrings. In this patch, we search and replace them with single whitespaces.
=> Remove double spaces

htmlgen/common.py, htmlgen/for_metamodel.py, htmlgen/main.py
We missed that each model would have a separate CSS and JS. This is unnecessary, and can slow down the development. We move CSS and JS to the root of HTML, and share them among the models.
=> Move CSS and JS to roof of the HTML

aas_core_meta/v3.py
The constraints AASd 50 and 50b have been removed in V3, and we propagate the changes to our meta-model.
=> Remove constraints AASd 50 and 50b in V3

aas_core_meta/v3.py, tests/test_v3.py
We introduce an abstract class, `Abstract_lang_string`, and many other derived concrete classes to model the langStrings of different length, as specified in the book.
The abstract class `Abstract_lang_string` is explicitly modelled without the model type in order to avoid confusion for the reader of JSON and XML schemas.
=> Introduce abstract lang string to V3

aas_core_meta/v3.py
The constrained primitive `Short_name` is not used in the metamodel anymore. We remove it since it seems redundant for the moment.
=> Remove `Short_name` from V3

aas_core_meta/v3.py
We fix the URL to point to IETF instead of Wikipedia, as it is more precise.
=> Fix URL to BCP 47 in the docs of V3

aas_core_meta/v3.py, tests/test_v3.py
The extension's `refers_to` property is made to a list to reflect changes in the book.
=> Make `refers_to` a list in V3

aas_core_meta/v3.py
The constrained primitive `Name_type` limits the length of the `name` property of the `Extension`. This reflects the specs in the book.
=> Limit extension's `name` to `Name_type`

aas_core_meta/v3.py
We update the data specifications in V3 to follow more closely the book.
Namely:
* We fix the constraint identifiers and corresponding invariants,
* We change the types of the properties accordingly,
* We shuffle the order of the properties to reflect better the tables in the book, and
* We update the documentation, where applicable.
=> Update data specifications in V3

aas_core_meta/v3.py
We mistakenly wrote external references in V3 where global references were appropriate.
=> Fix external *vs* global reference in V3

aas_core_meta/v3.py
We fix the erroneous description of the constant set `AAS_submodel_elements_as_keys`.
=> Fix description of AAS sub. elements as keys in V3

aas_core_meta/v3.py, tests/test_v3.py
We follow Merriam-Webster [1] and StackOverflow [2], and spell "ID" uppercase as initialism.
Due to shadowing, we had to rename the *type*, a constrained primitive, `ID_short` to `ID_short_type`.
[1]: https://www.britannica.com/dictionary/ID[2]
[2]: https://stackoverflow.com/questions/1151338/id-or-id-on-user-interface
=> Make "ID" an abbreviation in V3

htmlgen/.gitignore, htmlgen/for_metamodel.py, htmlgen/main.py
It is often very hard to figure out who implements a given parent class, so we list all the concrete descendants in that class page for easier browsing.
=> Generate list of concrete descendants in htmlgen

aas_core_meta/v3.py
See #215
Class AdministrativeInformation: Chapter 5.3.2.2, page 55
https://nextcloud.s-heppner.com/index.php/s/2KZr2kHoSTjkSoi#page=55
The new types: Chapter 5.3.11.2, page 103
https://nextcloud.s-heppner.com/index.php/s/2KZr2kHoSTjkSoi#page=103
=> Adapt types of `Administrative_information` version and revision

aas_core_meta/v3.py, htmlgen/for_metamodel.py
(case insensitive checking of string) 
See #205
AASd-116 
> "globalAssetId" (case-insensitive) is a reserved key. If used as value for SpecificAssetId/name, SpecificAssetId/value shall be identical to AssetInformation/globalAssetId.
> Note: AASd-116 is important to enable a generic search across global and specific asset IDs.
(Chapter 5.3.12.5, page 112)
https://nextcloud.s-heppner.com/index.php/s/2KZr2kHoSTjkSoi#page=112
AASd-116 asks for case-insensitive checking of the key "globalAssetId". We diverge from this and write an explanation as to why.
=> Add documentation for why diverging from the spec at AASd-116

.idea/aas-core-meta.iml, aas_core_meta/v3.py
See #204.
We confused AASd-119 and AASd-129 at several points of aas-core-meta, considering they are similar. This confusion has now been resolved: https://github.com/aas-core-works/aas-core-meta/issues/204#issuecomment-1429287012
Chapter 5.3.12.3, page 112
https://nextcloud.s-heppner.com/index.php/s/2KZr2kHoSTjkSoi#page=112
Now, AASd-129 needs to be fully implemented, before this PR loses WIP status
=> Fix Qualifiable invariants 

aas_core_meta/v3.py
We propagate the changes discussed in the last meeting of the IDTA
worsktream AAS.
Fixes #208.
Fixes #209.
=> Adapt type of value in Data_spec_IEC_61360 and Value_reference_pair

aas_core_meta/v3.py, aas_core_meta/v3rc2.py, htmlgen/for_metamodel.py
While aas-core-meta team works closely with IDTA, it is not *officially*
part of it.
We make this distinction a bit more explicit in the documentation of
the meta-models.
=> Highlight separation from IDTA in the docs

aas_core_meta/v3.py
We add a suffix `-work-in-progress` to let the readers know that this
version of the meta-model is still not complete, and is expected to 
change in the very near future.
=> Add "WIP" to version to avoid confusion

aas_core_meta/v3.py
Rework the explanation for why two implementations 
of the enumeration `AAS_submodel_elements` exist in the model.
Fixes #232
=> [V3.0] Reformulate confusing paragraph in module docstring

aas_core_meta/v3.py
The patterns in version and revision type had slashes as invalid prefixes and suffixes.
=> [V3] Fix version and revision types

aas_core_meta/v3.py
We fix the invariant of ``Administrative_information`` for the ``revision`` property, which contained a reference to ``version`` by a copy-paste error.
We also adjust the invariant messages for readability in downstream code.
=> [V3] Fix invariants for ``Administrative_information``

aas_core_meta/v3.py
We fix the length invariants for `version` and `revision` of `Administrative_information`. At this point, we also fix the texts of the invariants for readability in downstream applications.
=> [V3] Fix len. invariant for version and revision

aas_core_meta/v3.py
We add a nullability check which has not been discovered by our (admittedly still limited) type inference during the smoke test.
=> [V3] Fix invariant for Constraint AASd-129

aas_core_meta/v3.py
We omitted by mistake a nullability check which was revealed by mypy in Python SDK.
=> [V3] Check nullability in invariant of AASd-014

aas_core_meta/v3.py
The logic for the constraint AASd-131 has been incorrectly implemented. Namely, the implementation used the logical "or" instead of "exclusive or".
=> [V3] Fix either-or logic in AASd-131

aas_core_meta/v3.py, tests/test_v3.py
We omitted to use ``kind_or_default`` by mistake, and used ``kind`` instead.
=> [V3] Fix invariant for AASd-119 to use default

aas_core_meta/v3.py
We had another look at the text of the invariant:
> Constraint AASd-129: If any qualifier kind value of a Submodel element
> qualifier is equal to TemplateQualifier then the submodel element shall
> be part of a submodel template, i.e. a Submodel with submodel kind
> value is equal to "Template".
We understand it in a simplified form as follows.
If any qualifier of a submodel element is a template qualifier, then the submodel kind is equal to "Template".
We adapt the logic of the submodel invariant accordingly.
=> [V3] Follow text to re-write logic of AASd-129

aas_core_meta/v3.py
We got the logic wrong in #249. Namely, when a submodel element has no qualifiers, the predicate are still satisfied and imply that the submodel has to be a template.
This patch (hopefully) solves the issue. We tested the logic preliminary on aas-core3.0-testgen and it seems to work.
=> Fix invariant for AASd-129

aas_core_meta/v3.py
There exists no `submodel template_ID`.
What is meant here is the ID of a submodel template`. This typo is fixed to avoid confusion.
=> [v3.0] Fix typo in docstring of Administrative_information

aas_core_meta/v3.py
`Reference_type.Global_reference` was renamed to `External_reference` in order to avoid confusion with the seperate `Key_types.Global_reference`
=> [v3.0] Remove occurances of global references in docstring of `Reference`

aas_core_meta/v3.py
The invariant related to category ``VALUE`` seems to be off as it does not match the text description of the invariant.
Related to #251.
=> [V3] Remove dubious invariant from Concept Descr.

aas_core_meta/v3.py, tests/test_v3.py
We noticed that there were style inconsistencies in the invariants (with ending dot and without, camel-case names *etc.*). Additionally, some references were linked, some were not *etc.*.
We go over the meta-model and try to fix as many inconsistencies as possible.
=> [V3] Polish invariants and references

aas_core_meta/v3.py, setup.py, tests/test_v3.py
We use type strengthening instead of invariants so that compilers can detect null exceptions at compile time.
=> [V3] Use type strengthening for AASd-117

aas_core_meta/v3.py, tests/test_v3.py
We misinterpreted Constraint AASd-117, and made ID-shorts required in identifiables.
This patch fixes the issue by making ID-shorts optional in `Identifiable` class again.
=> [V3] Make ID-shorts optional in `Identifiable`

aas_core_meta/v3.py
We fix documentation findings:
* Remove references to `Data_type_def` from the module docstring, as
it has been removed in v3.0 of the spec.  Fixes #231.
* Add missing spec docstring to `Key.type`. Fixes #242.
* Expand description to `AAS_referables` to include its necessity to
exist, since this enum does not exist in the spec. Fixes #246 
* Document in the module docstring that `AASc-3a-003` cannot be 
implemented. Fixes #251.
* Document in the module docstring, how `Lang_string`-subtypes are 
implemented. Fixes #262.
=> [V3] Improve documentation

htmlgen/description.py, htmlgen/for_metamodel.py, htmlgen/main.py, precommit.py, pylint.rc, setup.py, tests/common.py, tests/test_v3.py, tests/test_v3rc2.py
We run pylint on htmlgen and tests to detect issues in code. We skip the meta-models intentionally, as they do not conform to "normal" code expected by pylint.
=> Detect issues in code with pylint

htmlgen/for_metamodel.py, setup.py
Currently, only concrete descendants are listed in the generated HTML documentation. However, many readers want to see a full list of descendants, and not only the concrete ones.
Therefore, we introduced ``descendants`` property in [aas_core_codegen.intermediate.Class], and leverage it in this patch.
[aas_core_codegen.intermediate.Class]: https://github.com/aas-core-works/aas-core-codegen/blob/b2c0e4a8e5622d2718371a5999d4aa3be9a9af9b/aas_core_codegen/intermediate/_types.py#L1437
=> List all descendants of a cls in html-doc

aas_core_meta/v3.py
We mistakenly checked for nullability instead of *non-nullability* in the constraint AASc-3a-009.
=> [V3] Fix nullability check in AASc-3a-009

aas_core_meta/v3.py
We forgot to use `kind_or_default`, which is a non-nullable, and used a `kind`, which can be `None`. The patch fixes this issue.
=> Fix nullability check in AASd-129

aas_core_meta/v3rc2.py, tests/test_v3rc2.py
We missed to ensure non-nullability in various invariants, and fix them in this patch. This was revealed once we implemented stricter nullability checks in aas-core-codegen, which is to be merged in shortly.
=> [V3RC2] Fix nullability checks in invariants

aas_core_meta/v3.py
We erroneously intertwined the remarks and constraints in some of the docstrings. Moreover, some notes were not properly indented, and were thus parsed as remarks instead of notes referring to the respective constraint.
This is directly related to [the issue #16 in aas-core3.0-csharp].
[the issue #16 in aas-core3.0-csharp]: https://github.com/aas-core-works/aas-core3.0-csharp/issues/16
=> Fix indention for notes in constraints

aas_core_meta/marker.py, aas_core_meta/v3.py, aas_core_meta/v3rc2.py, htmlgen/for_metamodel.py, htmlgen/main.py, setup.py
The original meta-model book has been split into different parts, and there is no single book anymore. We therefore deprecate the references in the book as their maintenance over different books would be too cumbersome.
Instead, we fix a single version for the meta-model and the single XML namespace.
=> Deprecate reference in the book

aas_core_meta/marker.py, aas_core_meta/v3.py, setup.py
We introduce the marker `non_mutating` to mark instance methods as non-mutating, *i.e.*, "const" in C++ jargon.
This is necessary so that we can generate later tighter code in C++ and related languages with "const" qualifiers for the member functions.
=> Add `non_mutating` marker

aas_core_meta/v3.py
We misinterpreted the text of the constraint AASd-131. We understood "Either ... or ..." as an exclusive OR, whereas it should be understood as inclusive OR.
Fixes #278.
=> [V3] Fix inclusive OR in AASd-131

aas_core_meta/v3.py
We misinterpreted the text of the constraint AASc-3a-010. It does *not* mean an exclusive OR, but rather a NAND. Both `value` and `value_list` *should not* be specified.
This patch adjusts the code to fit the text, to the best of our understanding.
We also remove the redundant part of the constraint related to the length of `value_reference_pairs` of `value_list` as that is already verified in the class `Value_list`.
Fixes #279.
=> [V3] Fix AASc-3a-010-for-NAND

.idea/aas-core3-meta.iml, htmlgen/common.py, htmlgen/description.py, htmlgen/for_metamodel.py, htmlgen/naming.py, htmlgen/transpilation.py, setup.py
We change the naming so that URIs can be used as URLs from `https://admin-shell.io/AAS/3/0` and future versions.
At this point, we also implement code highlighting ourselves, so that the properties, enumerations and constants are clickable in the code.
=> Change naming in htmlgen

htmlgen/for_metamodel.py
We fix naming for classes in inherited invariants.
=> Fix inheritance naming in htmlgen

htmlgen/for_metamodel.py
We forgot to add html-specific naming in titles, so we fix that in this commit.
=> Fix naming in titles in htmlgen

aas_core_meta/v3.py
We have to represent escapes in invariant descriptions as literals since Sphinx interpretes them as escaped characters otherwise. See [Sphinx docs] and [this StackOverflow question].
[Sphinx docs]: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#escaping-mechanism
[this StackOverflow question]: https://stackoverflow.com/questions/57265111/escape-special-characters-in-restructuredtext-sphinx
=> [V3] Fix invariant descriptions with escapes

aas_core_meta/v3.py
We made mistakes in the descriptions of the invariants for `Lang_string_short_name_type_IEC_61360` and 
`Lang_string_preferred_name_type_IEC_61360` where the descriptions
mismatched the invariant logic, which fits the specs.
This patch fixes the descriptions.
Fixes #288.
Fixes #289.
=> [V3] Fix invariant descriptions inconsistencies

htmlgen/for_metamodel.py, htmlgen/main.py, htmlgen/transpilation.py
We transpile pattern verification functions to HTML code. This is something we haven't done in codegen, and a bug eventually slipped in where the errors were unexpectedly silenced. Notable, the `re.match` function has not been set properly in the transpilation environment.
In this patch, we fix both the error reporting in the main program as well as the transpilation of pattern verifications.
Fixes #292.
=> Fix htmlgen for pattern verifications

aas_core_meta/v3.py
Previously, AASd-120 was already implemented as invariant, 
however it was not mentioned in the docstring of class 
`Submodel_element_list`.
This PR adds the missing mention in the docstring.
Fixes #294
=> Add missing docstring for AASd-120

aas_core_meta/v3.py, tests/test_v3.py
We fix the confusing messages of the constraints related to language strings. Namely, "Xxx specifies no duplicate languages" can be misunderstood such that `Xxx` should actually specify duplicate languages, but does not.
Obviously, we want to specify unique languages in such properties.
Fixes #299.
=> [V3] Fix messages for duplicate languages

aas_core_meta/v3_1.py
A new enumeration value has been added to class `Asset_kind`, see 
[aas-specs#294](https://github.com/admin-shell-io/aas-specs/issues/294)
Note, that I didn't modify the unittests, as it would appear, there's 
no specific test for enum values. 
Fixes #302
=> V3.1: Add Role value to Asset_kind enumeration

aas_core_meta/v3_1.py
Previously, the `matches_id_short` regular expression only allowed letters, digits and underscores.
With the decision of
[aas-specs#295](https://github.com/admin-shell-io/aas-specs/issues/295), 
this condition was relaxed to allow also hyphens.
Fixes #304
=> V3.1: Relax matches_id_short regex.

aas_core_meta/v3_1.py
Previously, `Entity.entity_type` was mandatory, however v3.1 changes this.
We adapt the class defintion, as well as the invariant of AASd-014.
Fix #306
=> V3.1: Make Entity.entity_type optional

aas_core_meta/v3_1.py, tests/test_v3_1.py
This is the branch where all the changes regarding v3.1 will be introduced. 
As a final step, we should merge this branch into `main`.
=> [WIP] Add metamodel version 3.1 support

aas_core_meta/v3_1.py
Previously, the docstring of `Asset_kind.Not_applicable` did not 
reflect the newly added `Asset_kind.Role` attribute. 
With this change, we make it more precise.
=> Adapt Asset_kind docstring to be more precise

aas_core_meta/v3_1.py
With v3.1 of the specification, the docstring of `Has_kind.kind` 
was changed.
This reflects this change.
=> Adapt docstring of Has_kind

aas_core_meta/v3_1.py
With v3.1 of the specification, the regex of `matches_id_short_type()` 
changed.
While this change has already been adapted, we forgot to adapt the 
docstring of class `ID_short_type`. 
This fixes this oversight.
=> Adapt docstring of ID_short_type

aas_core_meta/v3.py, tests/test_v3.py
We incorrectly did not group the offset for `+14:00` or `-14:00`, so it could be directly concatenated to the year in `xs:date`'s.
This patch fixes the issue, so the incorrect dates are correctly recognized.
=> [V3] Fix the pattern in xs:date for offset

aas_core_meta/v3.py, tests/test_v3.py
We incorrectly did not group the offset for `+14:00` or `-14:00`, so it could be directly concatenated as prefix in `xs:dateTime`'s.
This patch fixes the issue, so the incorrect date-times are correctly recognized.
=> [V3] Fix the pattern in xs:dateTime for offset

aas_core_meta/v3_1.py
We propagate the fix in #320 from V3 to V3.1 where a time zone offset of `14:00` without a sign was mistakenly accepted by
the regular expressions.
=> Propatage the fix for time offset from V3 to V3.1

aas_core_meta/v3.py, aas_core_meta/v3_1.py
We mistakenly transcribed from the book. We made the `data_specification` attribute required, while the book prescribes an optional field.
Fixes #326.
=> Fix optional in `Embedded_data_specification`

aas_core_meta/v3.py, aas_core_meta/v3_1.py
In #328, we made the attribute `data_specification` in class 
`Embedded_data_specification` optional, 
since that is what we thought the specification said.
(See also the discussion in #326)
However, this was a bug in the specification, which is fixed 
in v3.0.1 of the specification.
We therefore revert these changes.
Fixes #326
=> Revert Optional in Embedded_data_specification

aas_core_meta/v3.py
Currently, the regex for Path type is non-compliant
to the specification v3.0.1, as it does not allow for 
AASX packages to be written.
As a temporary bugfix in v3.0.1, it was decided 
to remove the invariant check, as changing the 
pattern would result in a breaking change.
This is of course no final solution, 
there will be a better fix for version 3.1.
See also [admin-shell-io/aas-specs#299](https://github.com/admin-shell-io/aas-specs/issues/299)
=> Remove `matches_RFC_8089_path` invariant from `Path_type`

htmlgen/description.py, setup.py
We update the code in `htmlgen` module to use the
`aas_core_codegen.intermediate.doc` instead of
`aas_core_codegen.intermediate.rendering` dependency. In aas-core-codegen, we merged `renderin` and `doc` modules in its revision 39980e50.
We update to the latest [aas-core-codegen bd310fc2] for maintenance.
[aas-core-codegen bd310fc2]: https://github.com/aas-core-works/aas-core-codegen/commit/bd310fc2
=> Update htmlgen to aas-core-codegen bd310fc2

aas_core_meta/v3.py, aas_core_meta/v3_1.py
This PR collects all changes for v3.0.1 of the specification. 
Here's a list of the changes. For easier reviewing, you can refer to the mentioned PRs.
Please forgive the unconventional use of PRs, but I need to generate the new schema files asap. 
**(See #329)**
In #328, we made the attribute `data_specification` in class `Embedded_data_specification` optional, since that is what we thought the specification said. See also the discussion in #326.
However, this was a bug in the specification, which is fixed in v3.0.1 of the specification. We therefore revert these changes.
Fixes #326.
**(See #333)**
Currently, the regex for Path type is non-compliant to the specification v3.0.1, as it does not allow for  AASX packages to be written.
As a temporary bugfix in v3.0.1, it was decided to remove …
=> [V3] Update to v3.0.1

aas_core_meta/v3.py
In version 3.0.2 of the specification of the AAS
Part 3a (IEC 613601 Data Specifiation),
constraint `AASc-002` is renamed to `AASc-3a-002`.
This PR reflects this change.
=> [V3] Rename constraint AASc-002 to AASc-3a-002

aas_core_meta/v3.py
In version 3.0.2 of the specification of the AAS Part 3a (IEC 613601 Data Specifiation), constraint `AASc-002` is renamed to `AASc-3a-002`.
This commit reflects this change.
@mristin This is #335 again, but this time pointed at `main` instead of the `DataSpec61360/v3.0.2` branch that turned out to be unnecessary, as there were no other changes in v3.0.2 of the Part 3a spec. 
Since it is purely documentative, it should not have any effect on codegen, however it would be nice to have in `main`.
=> Rename constraint AASc-002 to AASc-3a-002 (#335)

aas_core_meta/v3.py
Previously, we formalized Constraint AASd-109 such that it was not enforced as soon as the attribute ``value`` was not set. However, on a closer reading, it turns out that Constraint AASd-109 should be enforced even when no ``value`` is present.
Related to [aas-core3.0-csharp issue #38].
[aas-core3.0-csharp issue #38]: https://github.com/aas-core-works/aas-core3.0-csharp/issues/38
=> [V3] Fix AASd-109 for missing ``value``

aas_core_meta/v3.py
We fix the invariant AASd-109 for type inference as we erroneously included a non-nullness check for a non-optional attribute (``type_value_list_element``).
=> [V3] Fix AASd-109 for type inference

htmlgen/for_metamodel.py, htmlgen/transpilation.py, setup.py
We update to [aas-core-codegen ba0ca24c] for better type inference related to optional value types and nullness checks.
[aas-core-codegen ba0ca24c]: https://github.com/aas-core-works/aas-core-codegen/commit/ba0ca24c
=> Update aas-core-codegen to 6df5c9e8

aas_core_meta/v3_1.py
Previously, the invariant declaring the maximum length of `Identifier` was set to `2000`. We had already adapted this to `2024` according to [aas-specs#306](https://github.com/admin-shell-io/aas-specs/issues/306), however the decision was corrected to `2048` in [aas-specs#306](https://github.com/admin-shell-io/aas-specs/issues/306) and the specification adapted in [aas-specs#374](https://github.com/admin-shell-io/aas-specs/pull/374).
We therefore adapt the invariant to a maximum length of `2048`
Previously, the invariant declaring the maximum length of `Value_type_IEC_61360` was set to `2000`. Decided in [aas-specs#306](https://github.com/admin-shell-io/aas-specs/issues/306) and specified in [aas-specs-iec61360#21](https://github.com/admin-shell-io/aas-specs-iec61360/pull/21) this was …
=> V3.1: Adapt Identifier length to 2048

aas_core_meta/v3_1.py
Previously, `RelationshipElement.first` and `RelationshipElement.second` were mandatory attributes. As decided in [aas-specs#412](https://github.com/admin-shell-io/aas-specs/issues/412) and specified in [aas-specs#431](https://github.com/admin-shell-io/aas-specs/pull/431), we now make these attributes optional.
Furthermore, we extend these changes to the constructor of `AnnotatedRelationshipElement`.
Fixes #340
=> V3.1: Make first and second of RelationshipElement optional

aas_core_meta/v3_1.py
Previously, `File.content_type` and `Blob.content_type` were mandatory attributes. As decided in [aas-specs#412](https://github.com/admin-shell-io/aas-specs/issues/412) and specified in [aas-specs#431](https://github.com/admin-shell-io/aas-specs/pull/431), we now make these attributes optional.
Fixes #339
=> V3.1: Make content_type of File and Blob optional

aas_core_meta/v3_1.py
Version 3.1 of the metamodel changes the `Path_type` to be conforming to RFC 2396 (see [spec-link](https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/datatypes.html#PathType) ).
As we did not have a verifcation function for this RFC, we add the function `matches_RFC_2396` based on this [abnf_to_regexp test case](https://github.com/aas-core-works/abnf-to-regexp/blob/main/test_data/nested-python/rfc2396/expected.py) and adapt the `Path_type` invariant accordingly.
=> Add verifcation function for RFC 2396, adapt Path_type

aas_core_meta/v3_1.py
Previously, the pattern of `matches_xs_any_URI`  followed RFC 3987, which actually specifies IRIs. 
We adapt the pattern of this verification function to follow RFC 2396, as amended by RFC 2732, implementing the XSD v1.0 specification verbatim.
[XSD anyURI definition](https://www.w3.org/TR/xmlschema-2/#anyURI)
[RFC 2396](https://datatracker.ietf.org/doc/html/rfc2396)
[RFC 2732](https://datatracker.ietf.org/doc/html/rfc2732)
=> Adapt pattern of matches_xs_any_URI

aas_core_meta/v3.py
In #328, we had erroneously made `Embedded_data_specification.data_specification` optional, changing the order of the attributes of this class, as optional attributes have to be specified after mandatory ones.
In #329, we reverted the `Optional`, but kept the order of the attributes, as this didn't affect our code. However, as a result, the generated schema files that depend on the order of the attributes were suddenly not backward compatible anymore, as found in [aas-specs#477](https://github.com/admin-shell-io/aas-specs/issues/477).
This reverts the order of the attributes in class `Embedded_data_specification`.
=> [V3] Revert order of `Embedded_data_specification` attributes

aas_core_meta/v3_1.py
In v3.1, AASd-120 is relaxed from 
```
idShort of submodel elements being a direct child of a SubmodelElementList shall not be specified.
```
to
```
idShort of submodel elements being a direct child of a SubmodelElementList shall not be specified within Submodels with kind=Instance.
```
This makes the respective invariant not easily implementable, considering we would need to resolve the respective `Submodel` parent for a given `Submodel_element_list`.
We therefore remove the invariant check and document that we did not implement it.
See [aas-specs#432](https://github.com/admin-shell-io/aas-specs/issues/432).
=> V3.1: Remove AASd-120

aas_core_meta/v3_1.py
In v3.1 of the specification, the constraint AASd-116 was reformulated.
We adapt these changes.
See [aas-specs#298](https://github.com/admin-shell-io/aas-specs/issues/298) and [aas-specs#390](https://github.com/admin-shell-io/aas-specs/issues/390).
=> V3.1: Reformulate AASd-116

aas_core_meta/v3_1.py
Previously, class `Content_type` had a maximum length of 100 characters. This was changed to 128 in v3.1 of the specification.
See:
- Issue: [aas-specs#540](https://github.com/admin-shell-io/aas-specs/pull/540)
- PR: [aas-specs#543](https://github.com/admin-shell-io/aas-specs/pull/543)
- [Specification](https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/datatypes.html#ContentType)
=> V3.1 Update max length of Content_type

aas_core_meta/v3_1.py
We previously already removed AASd-120 in #358, but we appear to have missed two references to it
in the docstrings. This removes the now outdated references in the docstrings.
=> V3.1: Remove references to AASd-120 in docstrings

aas_core_meta/v3_1.py
Previously, `Value_reference_pair.value_id` was mandatory. In v3.1 it became optional.
See the [changelog](https://admin-shell-io.github.io/aas-specs-antora/IDTA-01003-a/v3.1/changelog.html#_changes_v3_1_vs_v3_0_2) (though it links to a wrong issue there).
=> V3.1: Make `Value_reference_pair.value_id` optional

aas_core_meta/v3_1.py
The definition of the `ID_shorts_are_unique` invariant was updated in v3.1 of the [specification](https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/spec-metamodel/common.html#Referable).
This reflects the change.
Fixes #319
=> v3.1: Update docstring of `ID_shorts_are_unique`

aas_core_meta/v3_1.py
This PR tracks the adapted changes of the specification for the version 3.1 release. 
Since it is now stable, it's ready to be merged/rebased into main. 
Fixes #303 
Fixes #305 
Fixes #317 
Fixes #319
Fixes #330
=> Adapt changes for specification v3.1

aas_core_meta/v3.py, aas_core_meta/v3_1.py
Previously, class `Value_data_type` inherited directly from `str`, when it should have been `Non_empty_XML_serializable_string`, as with every other string-class in the specification.
Since this was a bug with aas-core and not with the specification, this adapts class inheritance for both `v3.py` and `v3_1.py`.
Fixes #331
=> Fix inheritance of class `Value_data_type`

aas_core_meta/v3_1.py
Previously, some class attributes were made `Optional` in v3.1 of the specification. While this change was reflected in aas-core-meta, we missed to add a default value of `None` to their parameters in the constructor methods.
Affected by this are:
- `Entity.entity_type`
- `Value_data_type.value_id`
> [!warning]
> We need to make sure that the change of the `Entity` constructor is backward compatible!
> Does it change the order of the attributes in the schema files? 
> This could mean, that actually in practice, making an attribute `Optional` in the specification is actually not necessarily backward compatible in the schema!
Edit: After checking the generated schema files, I can confirm that the change is indeed backward compatible.
=> Add missing default values to constructors with optional parameters

aas_core_meta/v3_1.py
Previously, v3.1 of the specification changed the formulation of AASd-014 and made `Entity.entity_type` optional, see #311.
However, we missed adapting the implementation of invariant AASd-014, which we do here now.
=> [V3.1] Fix invariant implementation of AASd-014

aas_core_meta/v3.py, aas_core_meta/v3_1.py
We mistakenly constrained the Value Data Type to be non-empty by letting it inherit from *non-empty* XML-serializable string. This is incorrect as values can be empty, *e.g.*, when their semantics requires that.
=> [V3.0 and V3.1] Allow Value Data Type to be empty

aas_core_meta/v3.py, aas_core_meta/v3_1.py, aas_core_meta/v3rc2.py
AASd-128 requires that submodel element list entries in model reference paths are followed by an integer index in said list. In other places in the spec, this index is described as zero-based. Currently, the invariant for AASd-128, however, checks for the index to be a positive integer, *i.e.*, it excludes 0 from the set of valid values.
We instead constrain the index to non-negative integers to allow zero.
Fixes #369.
=> [V3.0 and V3.1] Fix references index constraint
